//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMondays.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gamertag> Gamertags { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MatchPerformanceSummary> MatchPerformanceSummaries { get; set; }
        public virtual DbSet<OverallRankingTable> OverallRankingTables { get; set; }
        public virtual DbSet<ResultsSummary> ResultsSummaries { get; set; }
        public virtual DbSet<AssistsSummary> AssistsSummaries { get; set; }
        public virtual DbSet<MapPerformanceSummary> MapPerformanceSummaries { get; set; }
        public virtual DbSet<ApiCallHistory> ApiCallHistories { get; set; }
        public virtual DbSet<MatchDate> MatchDates { get; set; }
    
        public virtual ObjectResult<MapPerformanceSummaryByMatchDate_Result> MapPerformanceSummaryByMatchDate(Nullable<System.DateTime> matchDate)
        {
            var matchDateParameter = matchDate.HasValue ?
                new ObjectParameter("MatchDate", matchDate) :
                new ObjectParameter("MatchDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MapPerformanceSummaryByMatchDate_Result>("MapPerformanceSummaryByMatchDate", matchDateParameter);
        }
    
        public virtual ObjectResult<OverallRankingTableByMatchDate_Result> OverallRankingTableByMatchDate(Nullable<System.DateTime> matchDate)
        {
            var matchDateParameter = matchDate.HasValue ?
                new ObjectParameter("MatchDate", matchDate) :
                new ObjectParameter("MatchDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OverallRankingTableByMatchDate_Result>("OverallRankingTableByMatchDate", matchDateParameter);
        }
    
        public virtual ObjectResult<ResultsSummaryByMatchDate_Result> ResultsSummaryByMatchDate(Nullable<System.DateTime> matchDate)
        {
            var matchDateParameter = matchDate.HasValue ?
                new ObjectParameter("MatchDate", matchDate) :
                new ObjectParameter("MatchDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResultsSummaryByMatchDate_Result>("ResultsSummaryByMatchDate", matchDateParameter);
        }
    
        public virtual ObjectResult<string> MapDistinctByMatchDate(Nullable<System.DateTime> matchDate)
        {
            var matchDateParameter = matchDate.HasValue ?
                new ObjectParameter("MatchDate", matchDate) :
                new ObjectParameter("MatchDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MapDistinctByMatchDate", matchDateParameter);
        }
    }
}
