//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMondays.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPerformanceSummary
    {
        public int Id { get; set; }
        public string MatchId { get; set; }
        public System.DateTime MatchCompletedDate { get; set; }
        public string GameMode { get; set; }
        public string Gamertag { get; set; }
        public string MapId { get; set; }
        public string MapName { get; set; }
        public int Rank { get; set; }
        public string Result { get; set; }
        public int Assists { get; set; }
        public int Kills { get; set; }
        public int Deaths { get; set; }
        public Nullable<decimal> KDRatio { get; set; }
    }
}
