//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMondays.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverallRankingTable
    {
        public Nullable<long> Rank { get; set; }
        public string Gamertag { get; set; }
        public Nullable<int> TotalKills { get; set; }
        public Nullable<int> TotalDeaths { get; set; }
        public Nullable<int> TotalAssists { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<decimal> KDRatio { get; set; }
    }
}
