//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMondays.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsSummary
    {
        public string Gamertag { get; set; }
        public string Result { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
